/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: "class",
    content: [
    "./*.html",
    ],
    theme: {
    extend: {
        colors: {
        "surface": "#121316",
        "on-secondary-container": "#b5b3c4",
        "on-tertiary-container": "#b67a58",
        "tertiary-container": "#3b1600",
        "on-background": "#e3e2e6",
        "tertiary": "#fcb791",
        "secondary-container": "#464553",
        "on-primary": "#1a3056",
        "inverse-on-surface": "#303033",
        "on-primary-fixed-variant": "#32476d",
        "on-error": "#690005",
        "primary-container": "#062045",
        "secondary-fixed-dim": "#c7c5d5",
        "secondary-fixed": "#e3e0f2",
        "on-primary-container": "#7488b3",
        "surface-container": "#1f1f22",
        "on-tertiary-fixed-variant": "#6a3b1e",
        "inverse-primary": "#4a5e87",
        "tertiary-fixed-dim": "#fcb791",
        "surface-container-lowest": "#0d0e11",
        "on-secondary-fixed": "#1a1a26",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#343538",
        "on-surface-variant": "#c4c6cf",
        "background": "#1C1C28",
        "error": "#ffb4ab",
        "on-secondary": "#2f2f3c",
        "on-primary-fixed": "#001a40",
        "surface-bright": "#38393c",
        "on-surface": "#e3e2e6",
        "secondary": "#c7c5d5",
        "text-primary": "#FFFFFF",
        "primary": "#b1c7f5",
        "surface-tint": "#b1c7f5",
        "primary-fixed-dim": "#b1c7f5",
        "on-secondary-fixed-variant": "#464553",
        "outline": "#8e9099",
        "surface-container-low": "#1b1b1e",
        "primary-fixed": "#d7e2ff",
        "outline-variant": "#44474e",
        "on-tertiary-fixed": "#331200",
        "surface-container-high": "#292a2d",
        "surface-variant": "#343538",
        "on-tertiary": "#4f250a",
        "text-secondary": "#E5E5E5",
        "surface-glow": "#020203",
        "tertiary-fixed": "#ffdbc9",
        "surface-dim": "#1C1C28",
        "inverse-surface": "#e3e2e6",
        "error-container": "#93000a",
    },
        borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
    },
        spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "margin-page": "5vw",
        "desktop-gutter": "24px",
        "mobile-gutter": "16px",
        "stack-lg": "32px",
    },
        fontFamily: {
        "body-lg": ["Sora"],
        "display-lg": ["Bebas Neue"],
        "headline-lg": ["Bebas Neue"],
        "headline-md": ["Bebas Neue"],
        "label-md": ["Space Grotesk"],
        "body-md": ["Sora"],
        "title-lg": ["Space Grotesk"],
    },
        fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "0.05em", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "title-lg": ["20px", { lineHeight: "1.4", fontWeight: "700" }],
        },
    },
},
    plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
],
};